#!/bin/sh
sudo arp-scan -I eth0 192.168.178.0/16 -gq | grep '192.' > scanresult.txt
#sudo arp-scan -I eth0 172.16.0.0/12 -gq | grep '172.' > scanresult.txt
#sudo arp-scan -I eth0 10.0.0.0/8 -gq | grep '10.' > scanresult.txt

python mappersons.py
cat personshome.txt
